# Read the Docs configuration file
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

build:
  os: 'ubuntu-24.04'
  tools:
    python: '3.12'
  jobs:
    # Use poetry to export optional + documentation dependencies
    post_create_environment:
      - python -m pip install poetry poetry-plugin-export
      - poetry export -o docs/requirements.txt --all-extras --with=docs
python:
  install:
    - requirements: docs/requirements.txt
