# Read the Docs configuration file
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

build:
  os: 'ubuntu-24.04'
  tools:
    python: '3.13'
  jobs:
    # Use uv to compile documentation dependencies
    post_create_environment:
      - python -m pip install uv
      - uv export -q --no-dev --group docs --no-emit-project -o docs/requirements.txt
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
